# docker-compose.yml
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_staging
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # Data တွေ မပျောက်အောင် Volume နဲ့ သိမ်းထားတာပါ
    restart: always

volumes:
  mongo_data: